@startuml

title __LIBRARYMANAGEMENTSYSTEM's Class Diagram__\n

  namespace controller {
    class controller.AddBookPage {
    }
  }
  

  namespace controller {
    class controller.AddUserPage {
    }
  }
  

  namespace controller {
    class controller.AlertHelper {
    }
  }
  

  namespace controller {
    class controller.IssueBookPage {
    }
  }
  

  namespace controller {
    class controller.LoginController {
    }
  }
  

  namespace controller {
    class controller.Main {
    }
  }
  

  namespace controller {
    class controller.MainMenuPage {
    }
  }
  

  namespace controller {
    class controller.ReturnBookPage {
    }
  }
  

  namespace controller {
    class controller.UserDetailsPage {
    }
  }
  

  namespace controller {
    class controller.ViewBooksPage {
    }
  }
  

  namespace model {
    class model.Book {
    }
  }
  

  namespace model {
    class model.Library {
    }
  }
  

  namespace model {
    class model.MyProg {
    }
  }
  

  namespace model {
    class model.Transaction {
    }
  }
  

  namespace model {
    class model.User {
    }
  }
  

  namespace model {
    enum UserType {
    }
  }
  

  controller.AddBookPage .up.|> javafx.fxml.Initializable
  controller.AddBookPage o-- model.Library : library
  controller.AddUserPage .up.|> javafx.fxml.Initializable
  controller.AddUserPage o-- model.Library : library
  controller.IssueBookPage .up.|> javafx.fxml.Initializable
  controller.IssueBookPage o-- model.Library : library
  controller.LoginController .up.|> javafx.fxml.Initializable
  controller.LoginController o-- model.Library : library
  controller.Main -up-|> javafx.application.Application
  controller.Main o-- model.Library : library
  controller.MainMenuPage .up.|> javafx.fxml.Initializable
  controller.MainMenuPage o-- model.Library : library
  controller.ReturnBookPage .up.|> javafx.fxml.Initializable
  controller.ReturnBookPage o-- model.Library : library
  controller.UserDetailsPage .up.|> javafx.fxml.Initializable
  controller.UserDetailsPage o-- model.Library : library
  controller.UserDetailsPage o-- model.User : selectedUser
  controller.ViewBooksPage .up.|> javafx.fxml.Initializable
  controller.ViewBooksPage o-- model.Library : library


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
